### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by dy** [mturley/jquery-react#1]
How is it going? Waiting for jquery plugin, rendering react as

```js
$('.selector').react(<App />)
```

and also `useJQuery` hook as

```js
const App = props => {
// acts like useRef, when content is rendered - invokes jquery effects
let $els = use$('.class')
$els.hide()

return <div className="class">App content</div> 
}
```

**Comment by dy** [comment]
@mturley any hope for response?

**Comment by mturley** [comment]
Hi @dy, I'm sorry for missing your original comment. Unfortunately this project never got off the ground and I don't think I will have time to work on it.

Also, The `useJQuery` part of this is not what the project was intending to accomplish, and I also never intended for anyone to actually consume this as a real library. It was a thought experiment for my own use, to help me learn more about React diffing and internal implementation; my intention was to implement an ultra-simplified and very-bad-performance version of React to explore the challenges and internal mechanisms of building something like React.

I plan to delete this repo soon. Sorry to disappoint :( you may want to check out https://reactjs.org/docs/integrating-with-other-libraries.html.

**Comment by mturley** [comment]
I should probably unpublish the package to free up the `jquery-react` name for someone else to use...

**Comment by dy** [comment]
I was thinking about making simple reactive aspects as `$(target).react(props => <>...</>)`.
For that purpose, there's [enhook](https://ghub.io/enhook) and [remorph](https://github.com/dy/remorph) are coming.
If you want, you can transfer pkg name to me `npm owner add dy jquery-react`.

**Comment by mturley** [comment]
What purpose do you have for using jQuery for that use case? You can just use `ReactDOM.render(props => <>...</>, document.querySelector(target))` for that right?

**Comment by dy** [comment]
@mturley not exactly. jQuery, first of all, wraps multiple elements, so reactive renderer will be applied to all elements in the set `$('.select').react(ReactSelect)`. Second, multiple reactions can be possibly added `$('.select').react(Provider).react(Component)` (not sure about the second).
Anyways, I feel like for jQuery people react ecosystem keeps forbidden, it requires installing deps, bundling and other difficult things. `jquery-react` can make it possible to just attach react components via unpkg.com/CDN in jquery-plugins way. There's a lot of websites not using bundling.

**Comment by mturley** [comment]
There's no need to use bundling to use React, that's a common misconception. If you don't need the benefits of a bundler you can just import it with a <script> tag. https://reactjs.org/docs/add-react-to-a-website.html. Multiple elements in a set could just be rendered with multiple render calls (`$('.select').each((index, element) => ReactDOM.render(Component, element))`) and multiple reactions can be handled with nested react components like you would do in a regular React app.

**Comment by dy** [comment]
There's a bunch of little improvements possible as well.
Eg. functional components, that have no main rendering effect, ie. do not modify own content but provide other side-effects, including jquery ones. That's different purpose than react.
```js
$('.dialog-btn').react(() => {
  let [showDialog, setShowDialog] = useState(false)
  $(this).on('click', e => setShowDialog(!showDialog))
  useEffect(() => showDialog ? dialog.show() : dialog.hide(), [showDialog])
})
```
Also that's cleaner and handy to have it chained, opposed to `each` constructions:
```js
$('.target').react(() => <>Content...</>).fadeIn()
```

Tbh I'm not sure I fully understand the point of your arguments, considering that you're not going to work on it anymore and were going to release the package name. Do you still want to keep the name and work on it? 

For me that's the most expected use-case - a jQuery plugin, that assigns react components to elements. Of course you can do anything with enough amount of knowledge, time and boilerplate code. But some things can be tricky to remember each time you're going to attach react to jquery, like multiaspects, undefined return or morphing the initial element, instead of rendering children as react does.

**Comment by mturley** [comment]
Sorry, no I was just curious about your use case. I'm not going to keep the name and work on it, you can have it. I'm still trying to understand what you'd like to do, but just out of my own curiosity. Go for it! I'll be interested to see what you create. I just added you as a maintainer on npm. I'll probably delete this repo eventually.

**Comment by dy** [comment]
If you'd prefer to keep the issues - you can transfer it to me or [scrapjs](https://github.com/scrapjs), for example

**Comment by mturley** [comment]
This is the only issue so far :D but sure, it doesn't matter either way, I'll transfer it to you and my dumb original little idea can live on in your commit history 😉
